### ISSUE TITLE
输出错误

### ISSUE THREAD

**Issue by Git950715** [helloworlde/SpringBootCollection#1]
按照示例去编写的时候，我的输出是输出不出来的，错误原因是：There was an unexpected error (type=Not Found, status=404)。404的话我起初是认为我的请求结果不是Json格式，转换为了跳转页面，输出的链接跳转不到对应的页面。但是我相同的接口返回的是Json格式的数据，所以这个猜测被否决了。还是认为是response那边有问题，最后查看是不是流写完了没有关的问题，response.getWriter().write(result);response.getWriter().close();后面加上关闭流就没有问题了。

**Comment by helloworlde** [comment]
哪个项目的哪个类，预期是什么，你的代码是什么

**Comment by Git950715** [comment]
SpringBoot-CustomResponse,CustomResponseReturnValueHandler,handleReturnValue。最后面的response输出。

**Comment by helloworlde** [comment]
HttpServletResponse 的流会在请求完成的时候由容器主动关闭，不需要主动去调用close方法，你可以看下你的代码其他地方是不是正确的

**Comment by Git950715** [comment]
但是我加了流关闭之后就没有问题了，没有关闭之后，<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Tue Sep 17 11:18:06 CST 2019</div><div>There was an unexpected error (type=Not Found, status=404).</div><div>No message available</div></body></html>就会有这样的返回。加了流关闭之后就正常返回了。

**Comment by helloworlde** [comment]
This application has no explicit mapping for /error 说明你有异常，看日志里面异常是什么再去处理

**Comment by Git950715** [comment]
我看了我的日志里面没有输出错误，

**Comment by Git950715** [comment]
response.getOutputStream().write(result.getBytes("UTF-8"));而且我用字符流输出也不会有问题
